name: publish-beta-to-npm

on:
  push:
    branches: [main]

jobs:
  publish-beta-to-npm:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: |
          node scripts/update-beta-package-version.js 
          cat benchmark/package.json | grep version
          cd benchmark && npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
