name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Upload to test store
        uses: blocklet/action-workflow@v1
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_TEST }}
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: true
          skip-release: true
          bundle-command: npm run bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
