name: publish-to-npm

on:
  push:
    branches: [main]

jobs:
  publish-beta-to-npm:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: |
          cat benchmark/package.json | grep version
          cd benchmark && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
